version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/php:8.2
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 'SHA256:Re+8XCZkBozEzRJcwfVSQJbyTn8yTJMhImvoy2WcalI'
      - run:
          name: Deploy to VPS
          command: |
            ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST \
            'cd /www/wwwroot/api-cvras.ddns.net/centralized_vehicle_rental_administration_system_be && \
            git pull origin main && \
            composer install --no-dev --optimize-autoloader && \
            php artisan migrate --force && \
            php artisan config:cache && \
            php artisan route:cache && \
            php artisan view:cache'

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
